/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Mega;

import java.awt.Color;
import java.awt.Font;
import javax.swing.*;
import java.util.Random;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableModel;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.PlainDocument;

/**
 *
 * @author RAFAEL ANDRADE DA SILVA RA: 2215100617
 */


public class MegasenaInterface extends javax.swing.JFrame {

    /**
     * Creates new form MegasenaInterface
     */
    public MegasenaInterface() {
        this.vetor = new int [6];
        this.matriz = new int[30][6];
        this.numero = new int[30][6];
        initComponents();
       
    }
    

    Random rand;
    int i,randomNum;
    int j,in,jogo,vet,tamanho,l,c;
    int x,y;
    
    
    int[][] numero;
    int[][] matriz;
    int[] vetor;
    
    
    public class TextDocument extends PlainDocument {
    /**
     * Tamanho máximo default do componente = 50 caracteres
     */
    private int tamanhoMax = 50;
 
    /**
     * Cria o validador com o tamanho máximo de 50
     */
    public TextDocument() {
        super();
    }
  
    /**
     * Cria o validador com o tamanho definido no parâmetro
     * 
     * @param tamanho Tamanho máximo da cadeia de caracteres
     */
    public TextDocument(int tamanho) {
        super();
        tamanhoMax = tamanho;
    }
 
        /**
     * A cada tecla pressionada valida a tecla verifica se não está no máximo que o campo pode aguentar.
     * 
         * @throws javax.swing.text.BadLocationException
     * @see javax.swing.text.Document#insertString(int, java.lang.String, javax.swing.text.AttributeSet)
     */
    @Override
    public void insertString(int offs, String str, AttributeSet a) 
         throws BadLocationException {
  
         if (str == null) return;
              
         String oldString = getText (0, getLength() );
         String newString = oldString.substring(0, offs) + str + oldString.substring(offs); 
                  
         if (newString.length() > tamanhoMax) {
             super.insertString(offs, "", a);
         } else {
             // Repassa para o pai.
             super.insertString(offs, str, a);
         }
                 
    }
 
}
    public class JTableUtilities
{

        /**
         *
         * @param table
         * @param alignment
         */
        public void setCellsAlignment(JTable table, int alignment)
    {
        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(alignment);

        TableModel tableModel = table.getModel();

        for (int columnIndex = 0; columnIndex < tableModel.getColumnCount(); columnIndex++)
        {
            table.getColumnModel().getColumn(columnIndex).setCellRenderer(rightRenderer);
        }
    }
    }

    /**
     *
     * @param par
     */
    public int[] GerarGame(){
        
        
        Metodos p;
        p = new Metodos();
        int j;
        
        
        for(j= 1;j<3001;j++){
            int i;
        for(i=0;i<6;i++)
    {
       //sorteio
       rand = new Random();
       randomNum = 1 + rand.nextInt(60);
       vetor[i] = randomNum;
       
    }
     repetir(vetor);
     p.ordenar(vetor);
     
     
     
    numero[i][0]= vetor[0];
    numero[i][1]= vetor[1];
    numero[i][2]= vetor[2];
    numero[i][3]= vetor[3];
    numero[i][4]= vetor[4];
    numero[i][5]= vetor[5];
    
    
    
        
        txtSorteioNum.add(String.format("Sorteio: [%1$04d] - %2$02d - %3$02d - %4$02d - %5$02d - %6$02d - %7$02d", j,
                                numero[i][0]  , numero[i][1] ,numero[i][2], numero[i][3], 
                                numero[i][4], + numero[i][5] , "\n")); 
        
        
        }
        
      return vetor;  
    }                                               

    
    
    void repetir(int vetor[]){
        int i,j,aux;

        for (i=0;i<6;i++)
        {
        for (j=i+1;j<=5;j++) 
        { 
        do{
        if (vetor[j] == vetor[i])
        { 
        vetor[j]= 1 + rand.nextInt(60);
        }
        } while(vetor[j] == vetor[i]);
        }
        }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Painelprincipal = new javax.swing.JPanel();
        jogador1 = new javax.swing.JLabel();
        jogador2 = new javax.swing.JLabel();
        jogador3 = new javax.swing.JLabel();
        dezna1 = new javax.swing.JLabel();
        dezna2 = new javax.swing.JLabel();
        dezna3 = new javax.swing.JLabel();
        PainelNumerosorteados = new javax.swing.JPanel();
        txtSorteioNum = new java.awt.List();
        txtResu = new javax.swing.JLabel();
        Paineldosjogadores = new javax.swing.JPanel();
        jScrollPane23 = new javax.swing.JScrollPane();
        tbJogosfeitos = new javax.swing.JTable();
        PainelResultadoganhador = new javax.swing.JPanel();
        txtNomeJogador1 = new javax.swing.JTextField();
        nom1 = new javax.swing.JLabel();
        acertos = new javax.swing.JLabel();
        txtAcerJogadorj1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNomeJogador2 = new javax.swing.JTextField();
        txtAcerJogadorj2 = new javax.swing.JTextField();
        txtNomeJogador3 = new javax.swing.JTextField();
        txtAcerJogadorj3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtJogador1 = new javax.swing.JTextField();
        txtJogador2 = new javax.swing.JTextField();
        txtJogador3 = new javax.swing.JTextField();
        J1dez1 = new javax.swing.JTextField();
        J1dez2 = new javax.swing.JTextField();
        J1dez3 = new javax.swing.JTextField();
        J1dez4 = new javax.swing.JTextField();
        J1dez5 = new javax.swing.JTextField();
        J1dez6 = new javax.swing.JTextField();
        J2dez1 = new javax.swing.JTextField();
        J2dez2 = new javax.swing.JTextField();
        J2dez3 = new javax.swing.JTextField();
        J2dez4 = new javax.swing.JTextField();
        J2dez5 = new javax.swing.JTextField();
        J2dez6 = new javax.swing.JTextField();
        J3dez1 = new javax.swing.JTextField();
        J3dez2 = new javax.swing.JTextField();
        J3dez3 = new javax.swing.JTextField();
        J3dez4 = new javax.swing.JTextField();
        J3dez5 = new javax.swing.JTextField();
        J3dez6 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tbControles = new javax.swing.JPanel();
        btnGravarJogos = new javax.swing.JButton();
        btnGerarSorteio = new javax.swing.JButton();
        btnResultado = new javax.swing.JButton();
        btnLimpartudo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simulador de Sorteio  .:: MEGA SENA::.");
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setMaximumSize(new java.awt.Dimension(0, 0));
        setMinimumSize(new java.awt.Dimension(1094, 572));
        setPreferredSize(new java.awt.Dimension(1156, 572));
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));

        Painelprincipal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        Painelprincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jogador1.setText("Jogador 1");
        Painelprincipal.add(jogador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jogador2.setText("Jogador 2");
        Painelprincipal.add(jogador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jogador3.setText("Jogador 3");
        Painelprincipal.add(jogador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        dezna1.setText("Dezena J1");
        Painelprincipal.add(dezna1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, -1, -1));

        dezna2.setText("Dezena J2");
        Painelprincipal.add(dezna2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, -1, -1));

        dezna3.setText("Dezena J3");
        Painelprincipal.add(dezna3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, -1, -1));

        PainelNumerosorteados.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "NUMEROS SOTEADOS"));

        txtSorteioNum.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtSorteioNum.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        txtSorteioNum.setForeground(new java.awt.Color(0, 0, 204));

        txtResu.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        txtResu.setForeground(new java.awt.Color(0, 0, 204));

        javax.swing.GroupLayout PainelNumerosorteadosLayout = new javax.swing.GroupLayout(PainelNumerosorteados);
        PainelNumerosorteados.setLayout(PainelNumerosorteadosLayout);
        PainelNumerosorteadosLayout.setHorizontalGroup(
            PainelNumerosorteadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelNumerosorteadosLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(PainelNumerosorteadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtResu, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSorteioNum, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );
        PainelNumerosorteadosLayout.setVerticalGroup(
            PainelNumerosorteadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelNumerosorteadosLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(txtSorteioNum, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtResu, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                .addContainerGap())
        );

        Painelprincipal.add(PainelNumerosorteados, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, 270));

        Paineldosjogadores.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "TABELA DOS JOGOS"));

        tbJogosfeitos.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        tbJogosfeitos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "JOGADORES", "JOGOS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbJogosfeitos.setToolTipText("");
        tbJogosfeitos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tbJogosfeitos.setColumnSelectionAllowed(true);
        tbJogosfeitos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane23.setViewportView(tbJogosfeitos);
        tbJogosfeitos.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        PainelResultadoganhador.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "RESULTADO GANHADOR"));
        PainelResultadoganhador.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNomeJogador1.setEditable(false);
        txtNomeJogador1.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        PainelResultadoganhador.add(txtNomeJogador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 45, 244, -1));

        nom1.setText("NOME:");
        PainelResultadoganhador.add(nom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 52, -1, -1));

        acertos.setText("ACERTOS:");
        PainelResultadoganhador.add(acertos, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 94, -1, -1));

        txtAcerJogadorj1.setEditable(false);
        txtAcerJogadorj1.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        PainelResultadoganhador.add(txtAcerJogadorj1, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 87, 178, -1));

        jLabel3.setText("NOME:");
        PainelResultadoganhador.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 159, -1, -1));

        jLabel4.setText("NOME:");
        PainelResultadoganhador.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 243, -1, -1));

        jLabel5.setText("ACERTOS:");
        PainelResultadoganhador.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 193, -1, -1));

        jLabel6.setText("ACERTOS:");
        PainelResultadoganhador.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 271, -1, -1));

        txtNomeJogador2.setEditable(false);
        txtNomeJogador2.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        PainelResultadoganhador.add(txtNomeJogador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 137, 244, -1));

        txtAcerJogadorj2.setEditable(false);
        txtAcerJogadorj2.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        PainelResultadoganhador.add(txtAcerJogadorj2, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 179, 178, -1));

        txtNomeJogador3.setEditable(false);
        txtNomeJogador3.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        PainelResultadoganhador.add(txtNomeJogador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 215, 244, -1));

        txtAcerJogadorj3.setEditable(false);
        txtAcerJogadorj3.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        PainelResultadoganhador.add(txtAcerJogadorj3, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 257, 178, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mega vetor.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        PainelResultadoganhador.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 170, 170));

        javax.swing.GroupLayout PaineldosjogadoresLayout = new javax.swing.GroupLayout(Paineldosjogadores);
        Paineldosjogadores.setLayout(PaineldosjogadoresLayout);
        PaineldosjogadoresLayout.setHorizontalGroup(
            PaineldosjogadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaineldosjogadoresLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(PaineldosjogadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane23)
                    .addComponent(PainelResultadoganhador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29))
        );
        PaineldosjogadoresLayout.setVerticalGroup(
            PaineldosjogadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaineldosjogadoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane23, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PainelResultadoganhador, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Painelprincipal.add(Paineldosjogadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 510, 440));

        txtJogador1.setDocument(new TextDocument(20));
        Painelprincipal.add(txtJogador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 142, -1));

        txtJogador2.setDocument(new TextDocument(20));
        Painelprincipal.add(txtJogador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 142, -1));

        txtJogador3.setDocument(new TextDocument(20));
        Painelprincipal.add(txtJogador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 142, -1));

        J1dez1.setDocument(new TextDocument(2));
        J1dez1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        J1dez1.setMaximumSize(new java.awt.Dimension(20, 20));
        J1dez1.setMinimumSize(new java.awt.Dimension(20, 20));
        J1dez1.setName(""); // NOI18N
        J1dez1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                J1dez1ActionPerformed(evt);
            }
        });
        Painelprincipal.add(J1dez1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 30, 30));

        J1dez2.setDocument(new TextDocument(2));
        J1dez2.setMaximumSize(new java.awt.Dimension(20, 20));
        J1dez2.setMinimumSize(new java.awt.Dimension(20, 20));
        Painelprincipal.add(J1dez2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 30, 30));

        J1dez3.setDocument(new TextDocument(2));
        J1dez3.setMaximumSize(new java.awt.Dimension(20, 20));
        J1dez3.setMinimumSize(new java.awt.Dimension(20, 20));
        Painelprincipal.add(J1dez3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 30, 30));

        J1dez4.setDocument(new TextDocument(2));
        J1dez4.setMaximumSize(new java.awt.Dimension(20, 20));
        J1dez4.setMinimumSize(new java.awt.Dimension(20, 20));
        Painelprincipal.add(J1dez4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 30, 30));

        J1dez5.setDocument(new TextDocument(2));
        J1dez5.setMaximumSize(new java.awt.Dimension(20, 20));
        J1dez5.setMinimumSize(new java.awt.Dimension(20, 20));
        Painelprincipal.add(J1dez5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, 30, 30));

        J1dez6.setDocument(new TextDocument(2));
        J1dez6.setMaximumSize(new java.awt.Dimension(20, 20));
        J1dez6.setMinimumSize(new java.awt.Dimension(20, 20));
        Painelprincipal.add(J1dez6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, 30, 30));

        J2dez1.setDocument(new TextDocument(2));
        J2dez1.setMaximumSize(new java.awt.Dimension(10, 20));
        J2dez1.setMinimumSize(new java.awt.Dimension(10, 20));
        Painelprincipal.add(J2dez1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 30, 30));

        J2dez2.setDocument(new TextDocument(2));
        J2dez2.setMaximumSize(new java.awt.Dimension(10, 20));
        J2dez2.setMinimumSize(new java.awt.Dimension(10, 20));
        Painelprincipal.add(J2dez2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 30, 30));

        J2dez3.setDocument(new TextDocument(2));
        J2dez3.setMaximumSize(new java.awt.Dimension(10, 20));
        J2dez3.setMinimumSize(new java.awt.Dimension(10, 20));
        Painelprincipal.add(J2dez3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 30, 30));

        J2dez4.setDocument(new TextDocument(2));
        J2dez4.setMaximumSize(new java.awt.Dimension(10, 20));
        J2dez4.setMinimumSize(new java.awt.Dimension(10, 20));
        Painelprincipal.add(J2dez4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 30, 30));

        J2dez5.setDocument(new TextDocument(2));
        J2dez5.setMaximumSize(new java.awt.Dimension(10, 20));
        J2dez5.setMinimumSize(new java.awt.Dimension(10, 20));
        Painelprincipal.add(J2dez5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, 30, 30));

        J2dez6.setDocument(new TextDocument(2));
        J2dez6.setMaximumSize(new java.awt.Dimension(10, 20));
        J2dez6.setMinimumSize(new java.awt.Dimension(10, 20));
        Painelprincipal.add(J2dez6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 30, 30));

        J3dez1.setDocument(new TextDocument(2));
        J3dez1.setMaximumSize(new java.awt.Dimension(10, 20));
        J3dez1.setMinimumSize(new java.awt.Dimension(10, 20));
        Painelprincipal.add(J3dez1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 30, 30));

        J3dez2.setDocument(new TextDocument(2));
        J3dez2.setMaximumSize(new java.awt.Dimension(10, 20));
        J3dez2.setMinimumSize(new java.awt.Dimension(10, 20));
        Painelprincipal.add(J3dez2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 30, 30));

        J3dez3.setDocument(new TextDocument(2));
        J3dez3.setMaximumSize(new java.awt.Dimension(10, 20));
        J3dez3.setMinimumSize(new java.awt.Dimension(10, 20));
        Painelprincipal.add(J3dez3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 30, 30));

        J3dez4.setDocument(new TextDocument(2));
        J3dez4.setMaximumSize(new java.awt.Dimension(10, 20));
        J3dez4.setMinimumSize(new java.awt.Dimension(10, 20));
        Painelprincipal.add(J3dez4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 30, 30));

        J3dez5.setDocument(new TextDocument(2));
        J3dez5.setMaximumSize(new java.awt.Dimension(10, 20));
        J3dez5.setMinimumSize(new java.awt.Dimension(10, 20));
        Painelprincipal.add(J3dez5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 30, 30));

        J3dez6.setDocument(new TextDocument(2));
        J3dez6.setMaximumSize(new java.awt.Dimension(10, 20));
        J3dez6.setMinimumSize(new java.awt.Dimension(10, 20));
        Painelprincipal.add(J3dez6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, 30, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mega vetor.png"))); // NOI18N
        Painelprincipal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 170, 180));

        tbControles.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "CONTROLES"));
        tbControles.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGravarJogos.setText("GRAVAR JOGOS");
        btnGravarJogos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarJogosActionPerformed(evt);
            }
        });
        tbControles.add(btnGravarJogos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 203, -1));

        btnGerarSorteio.setText("GERAR SORTEIO");
        btnGerarSorteio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarSorteioActionPerformed(evt);
            }
        });
        tbControles.add(btnGerarSorteio, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 203, -1));

        btnResultado.setText("VERIFICAR RESULTADOS");
        btnResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResultadoActionPerformed(evt);
            }
        });
        tbControles.add(btnResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 185, -1));

        btnLimpartudo.setText("LIMPAR TUDO");
        btnLimpartudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpartudoActionPerformed(evt);
            }
        });
        tbControles.add(btnLimpartudo, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 40, 185, -1));

        Painelprincipal.add(tbControles, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, 870, 90));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Painelprincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 1094, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Painelprincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
        );

        setSize(new java.awt.Dimension(1120, 610));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResultadoActionPerformed
       
        int [] vet = vetor;
        
        //System.out.println(vet[0]);Integer.parseInt
        
        String j1dez1 = J1dez1.getText();String j1dez2 = J1dez2.getText();
        String j1dez3 = J1dez3.getText();String j1dez4 = J1dez4.getText();
        String j1dez5 = J1dez5.getText();String j1dez6 = J1dez6.getText();
        
        String j2dez1 = J1dez1.getText();String j2dez2 = J1dez2.getText();
        String j2dez3 = J1dez3.getText();String j2dez4 = J1dez4.getText();
        String j2dez5 = J1dez5.getText();String j2dez6 = J1dez6.getText();
        
        String j3dez1 = J1dez1.getText();String j3dez2 = J1dez2.getText();
        String j3dez3 = J1dez3.getText();String j3dez4 = J1dez4.getText();
        String j3dez5 = J1dez5.getText();String j3dez6 = J1dez6.getText();
        if (
              J1dez1.getText().equals("")  || J1dez2.getText().equals("") 
           || J1dez3.getText().equals("")  || J1dez4.getText().equals("") 
           || J1dez5.getText().equals("")  || J1dez6.getText().equals("") 
           
           || J2dez1.getText().equals("")  || J2dez2.getText().equals("") 
           || J2dez3.getText().equals("")  || J2dez4.getText().equals("") 
           || J2dez5.getText().equals("")  || J2dez6.getText().equals("")
           
           || J3dez1.getText().equals("")  || J3dez2.getText().equals("") 
           || J3dez3.getText().equals("")  || J3dez4.getText().equals("") 
           || J3dez5.getText().equals("")  || J3dez6.getText().equals("")  
                ){
           JOptionPane.showMessageDialog(null, "DEZENAS ESTÃO VAZIAS OU INVALIDAS !!!");
        
       }else{
        int j1dz1 = Integer.parseInt(J1dez1.getText());
        int j1dz2 = Integer.parseInt(J1dez2.getText());
        int j1dz3 = Integer.parseInt(J1dez3.getText());
        int j1dz4 = Integer.parseInt(J1dez4.getText());
        int j1dz5 = Integer.parseInt(J1dez5.getText());
        int j1dz6 = Integer.parseInt(J1dez6.getText());
        
        int j2dz1 = Integer.parseInt(J2dez1.getText());
        int j2dz2 = Integer.parseInt(J2dez2.getText());
        int j2dz3 = Integer.parseInt(J2dez3.getText());
        int j2dz4 = Integer.parseInt(J2dez4.getText());
        int j2dz5 = Integer.parseInt(J2dez5.getText());
        int j2dz6 = Integer.parseInt(J2dez6.getText());
        
        int j3dz1 = Integer.parseInt(J3dez1.getText());
        int j3dz2 = Integer.parseInt(J3dez2.getText());
        int j3dz3 = Integer.parseInt(J3dez3.getText());
        int j3dz4 = Integer.parseInt(J3dez4.getText());
        int j3dz5 = Integer.parseInt(J3dez5.getText());
        int j3dz6 = Integer.parseInt(J3dez6.getText());
        
        String njogador1 = txtJogador1.getText();
        String njogador2 = txtJogador2.getText();
        String njogador3 = txtJogador3.getText();
        
        int contj1 = 0;
        int contj2 = 0;
        int contj3 = 0;
           
        //Jogos acertados pelo jogador1
        if(vet[0] == j1dz1)contj1 += 1;if(vet[0] == j1dz2)contj1 += 1;   
        if(vet[0] == j1dz3)contj1 += 1;if(vet[0] == j1dz4)contj1 += 1; 
        if(vet[0] == j1dz5)contj1 += 1;if(vet[0] == j1dz6)contj1 += 1; 
        
        if(vet[1] == j1dz1)contj1 += 1;if(vet[1] == j1dz2)contj1 += 1;   
        if(vet[1] == j1dz3)contj1 += 1;if(vet[1] == j1dz4)contj1 += 1; 
        if(vet[1] == j1dz5)contj1 += 1;if(vet[1] == j1dz6)contj1 += 1; 
        
        if(vet[2] == j1dz1)contj1 += 1;if(vet[2] == j1dz2)contj1 += 1;   
        if(vet[2] == j1dz3)contj1 += 1;if(vet[2] == j1dz4)contj1 += 1; 
        if(vet[2] == j1dz5)contj1 += 1;if(vet[2] == j1dz6)contj1 += 1;
            
        if(vet[3] == j1dz1)contj1 += 1;if(vet[3] == j1dz2)contj1 += 1;
        if(vet[3] == j1dz3)contj1 += 1;if(vet[3] == j1dz4)contj1 += 1;
        if(vet[3] == j1dz5)contj1 += 1;if(vet[3] == j1dz6)contj1 += 1;
        
        if(vet[4] == j1dz1)contj1 += 1;if(vet[4] == j1dz2)contj1 += 1;
        if(vet[4] == j1dz3)contj1 += 1;if(vet[4] == j1dz4)contj1 += 1;
        if(vet[4] == j1dz5)contj1 += 1;if(vet[4] == j1dz6)contj1 += 1;
            
        if(vet[5] == j1dz1)contj1 += 1;if(vet[5] == j1dz2)contj1 += 1;   
        if(vet[5] == j1dz3)contj1 += 1;if(vet[5] == j1dz4)contj1 += 1; 
        if(vet[5] == j1dz5)contj1 += 1;if(vet[5] == j1dz6)contj1 += 1;
        
         //Jogos acertados pelo jogador2
        if(vet[0] == j2dz1)contj2 += 1;if(vet[0] == j2dz2)contj2 += 1;   
        if(vet[0] == j2dz3)contj2 += 1;if(vet[0] == j2dz4)contj2 += 1; 
        if(vet[0] == j2dz5)contj2 += 1;if(vet[0] == j2dz6)contj2 += 1; 
        
        if(vet[1] == j2dz1)contj2 += 1;if(vet[1] == j2dz2)contj2 += 1;   
        if(vet[1] == j2dz3)contj2 += 1;if(vet[1] == j2dz4)contj2 += 1; 
        if(vet[1] == j2dz5)contj2 += 1;if(vet[1] == j2dz6)contj2 += 1; 
        
        if(vet[2] == j2dz1)contj2 += 1;if(vet[2] == j2dz2)contj2 += 1;   
        if(vet[2] == j2dz3)contj2 += 1;if(vet[2] == j2dz4)contj2 += 1; 
        if(vet[2] == j2dz5)contj2 += 1;if(vet[2] == j2dz6)contj2 += 1;
            
        if(vet[3] == j2dz1)contj2 += 1;if(vet[3] == j2dz2)contj2 += 1;
        if(vet[3] == j2dz3)contj2 += 1;if(vet[3] == j2dz4)contj2 += 1;
        if(vet[3] == j2dz5)contj2 += 1;if(vet[3] == j2dz6)contj2 += 1;
        
        if(vet[4] == j2dz1)contj2 += 1;if(vet[4] == j2dz2)contj2 += 1;
        if(vet[4] == j2dz3)contj2 += 1;if(vet[4] == j2dz4)contj2 += 1;
        if(vet[4] == j2dz5)contj2 += 1;if(vet[4] == j2dz6)contj2 += 1;
            
        if(vet[5] == j2dz1)contj2 += 1;if(vet[5] == j2dz2)contj2 += 1;   
        if(vet[5] == j2dz3)contj2 += 1;if(vet[5] == j2dz4)contj2 += 1; 
        if(vet[5] == j2dz5)contj2 += 1;if(vet[5] == j2dz6)contj2 += 1;
        
         //Jogos acertados pelo jogador3
        if(vet[0] == j3dz1)contj3 += 1;if(vet[0] == j3dz2)contj3 += 1;   
        if(vet[0] == j3dz3)contj3 += 1;if(vet[0] == j3dz4)contj3 += 1; 
        if(vet[0] == j3dz5)contj3 += 1;if(vet[0] == j3dz6)contj3 += 1; 
        
        if(vet[1] == j3dz1)contj3 += 1;if(vet[1] == j3dz2)contj3 += 1;   
        if(vet[1] == j3dz3)contj3 += 1;if(vet[1] == j3dz4)contj3 += 1; 
        if(vet[1] == j3dz5)contj3 += 1;if(vet[1] == j3dz6)contj3 += 1; 
       
        if(vet[2] == j3dz1)contj3 += 1;if(vet[2] == j3dz2)contj3 += 1;   
        if(vet[2] == j3dz3)contj3 += 1;if(vet[2] == j3dz4)contj3 += 1; 
        if(vet[2] == j3dz5)contj3 += 1;if(vet[2] == j3dz6)contj3 += 1;
            
        if(vet[3] == j3dz1)contj3 += 1;if(vet[3] == j3dz2)contj3 += 1;
        if(vet[3] == j3dz3)contj3 += 1;if(vet[3] == j3dz4)contj3 += 1;
        if(vet[3] == j3dz5)contj3 += 1;if(vet[3] == j3dz6)contj3 += 1;
        
        if(vet[4] == j3dz1)contj3 += 1;if(vet[4] == j3dz2)contj3 += 1;
        if(vet[4] == j3dz3)contj3 += 1;if(vet[4] == j3dz4)contj3 += 1;
        if(vet[4] == j3dz5)contj3 += 1;if(vet[4] == j3dz6)contj3 += 1;
            
        if(vet[5] == j3dz1)contj3 += 1;if(vet[5] == j3dz2)contj3 += 1;   
        if(vet[5] == j3dz3)contj3 += 1;if(vet[5] == j3dz4)contj3 += 1; 
        if(vet[5] == j3dz5)contj3 += 1;if(vet[5] == j3dz6)contj3 += 1;
       
        
        txtNomeJogador1.setForeground(Color.blue);
        txtNomeJogador2.setForeground(Color.blue);
        txtNomeJogador3.setForeground(Color.blue);
        
        txtAcerJogadorj1.setForeground(Color.blue);
        txtAcerJogadorj2.setForeground(Color.blue);
        txtAcerJogadorj3.setForeground(Color.blue);
        
        txtNomeJogador1.setText(njogador1);
        txtNomeJogador2.setText(njogador2);
        txtNomeJogador3.setText(njogador3);
        
        txtAcerJogadorj1.setText(String.valueOf(contj1));
        txtAcerJogadorj2.setText(String.valueOf(contj2));
        txtAcerJogadorj3.setText(String.valueOf(contj3));
        
        
        
            
        }
    }//GEN-LAST:event_btnResultadoActionPerformed

    private void btnGerarSorteioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarSorteioActionPerformed
        
        String nomej1;String nomej2;String nomej3;
        
        nomej1 = txtJogador1.getText();nomej2 = txtJogador2.getText();nomej3 = txtJogador3.getText();

        //DEZENAS JOGADOR 1
        String j1dez1 = J1dez1.getText();String j1dez2 = J1dez2.getText();
        String j1dez3 = J1dez3.getText();String j1dez4 = J1dez4.getText();
        String j1dez5 = J1dez5.getText();String j1dez6 = J1dez6.getText();    
        
        //DEZENAS JOGADOR 2
        String j2dez1 = J2dez1.getText();String j2dez2 = J2dez2.getText();
        String j2dez3 = J2dez3.getText();String j2dez4 = J2dez4.getText();
        String j2dez5 = J2dez5.getText();String j2dez6 = J2dez6.getText();  
        
        //DEZENAS JOGADOR 3
        String j3dez1 = J3dez1.getText();String j3dez2 = J3dez2.getText();
        String j3dez3 = J3dez3.getText();String j3dez4 = J3dez4.getText();
        String j3dez5 = J3dez5.getText();String j3dez6 = J3dez6.getText();  
        
        
        
       
       if ("".equals(nomej1)     || j1dez1.equals(j1dez2) 
        || j1dez1.equals(j1dez3) || j1dez1.equals(j1dez4) 
        || j1dez1.equals(j1dez5) || j1dez1.equals(j1dez6) 
        || j1dez2.equals(j1dez3) || j1dez2.equals(j1dez4)
        || j1dez2.equals(j1dez5) || j1dez2.equals(j1dez6) 
        || j1dez3.equals(j1dez4) || j1dez3.equals(j1dez5) 
        || j1dez3.equals(j1dez6) || j1dez4.equals(j1dez5)
        || j1dez5.equals(j1dez6) || j1dez5.equals(j1dez6)
        || "".equals(nomej2)     || j2dez1.equals(j2dez2) 
               //jogador2
        || j2dez1.equals(j2dez3) || j2dez1.equals(j2dez4)
        || j2dez1.equals(j2dez5) || j2dez1.equals(j2dez6)
        || j2dez2.equals(j2dez3) || j2dez2.equals(j2dez4)
        || j2dez2.equals(j2dez5) || j2dez2.equals(j2dez6)
        || j2dez3.equals(j2dez4) || j2dez3.equals(j2dez5)
        || j2dez3.equals(j2dez6) || j2dez4.equals(j2dez5)
        || j2dez5.equals(j2dez6) || j2dez5.equals(j2dez6)
               //jogador 3
        
        || j3dez1.equals(j3dez3) || j3dez1.equals(j3dez4)
        || j3dez1.equals(j3dez5) || j3dez1.equals(j3dez6)
        || j3dez2.equals(j3dez3) || j3dez2.equals(j3dez4)
        || j3dez2.equals(j3dez5) || j3dez2.equals(j3dez6)
        || j3dez3.equals(j3dez4) || j3dez3.equals(j3dez5)
        || j3dez3.equals(j3dez6) || j3dez4.equals(j3dez5)
        || j3dez5.equals(j3dez6) || j3dez5.equals(j3dez6)
        || "".equals(nomej3)
               ){
        
           JOptionPane.showMessageDialog(null, "Preencha os campos espertinho ! :D");

       }else{
        Metodos p;
        p = new Metodos();
        int j;
        
        
        for(j= 1;j<3001;j++){
            int i;
        for(i=0;i<6;i++)
    {
       //sorteio
       rand = new Random();
       randomNum = 1 + rand.nextInt(60);
       vetor[i] = randomNum;
       
    }
     repetir(vetor);
     p.ordenar(vetor);
     
     
     
    numero[i][0]= vetor[0];
    numero[i][1]= vetor[1];
    numero[i][2]= vetor[2];
    numero[i][3]= vetor[3];
    numero[i][4]= vetor[4];
    numero[i][5]= vetor[5];
    
    
    
        
        txtSorteioNum.add(String.format("Sorteio: [%1$04d] - %2$02d - %3$02d - %4$02d - %5$02d - %6$02d - %7$02d", j,numero[i][0]  , numero[i][1] ,numero[i][2], numero[i][3],numero[i][4], + numero[i][5] , "\n"));
        
        
        txtResu.setText(String.format("Sorteio: [%1$04d] - %2$02d - %3$02d - %4$02d - %5$02d - %6$02d - %7$02d",j,vetor[0], vetor[1], vetor[2], vetor[3], vetor[4] ,vetor[5],"\n"));
        }
        
       }
    }//GEN-LAST:event_btnGerarSorteioActionPerformed

    private void btnLimpartudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpartudoActionPerformed
        txtSorteioNum.clear();
        J1dez1.setText("");
        J1dez2.setText("");
        J1dez3.setText("");
        J1dez4.setText("");
        J1dez5.setText("");
        J1dez6.setText("");
        J2dez1.setText("");
        J2dez2.setText("");
        J2dez3.setText("");
        J2dez4.setText("");
        J2dez5.setText("");
        J2dez6.setText("");
        J3dez1.setText("");
        J3dez2.setText("");
        J3dez3.setText("");
        J3dez4.setText("");
        J3dez5.setText("");
        J3dez6.setText("");
        txtAcerJogadorj1.setText("");
        txtAcerJogadorj2.setText("");
        txtAcerJogadorj3.setText("");
        txtJogador1.setText("");
        txtJogador2.setText("");
        txtJogador3.setText("");
        txtNomeJogador1.setText("");
        txtNomeJogador2.setText("");
        txtNomeJogador3.setText("");
        DefaultTableModel tabela = (DefaultTableModel)tbJogosfeitos.getModel();
        tabela.setNumRows(0);
        txtResu.setText("");
        
        //Habilita novos jogadores
       txtJogador1.enable(true);txtJogador2.enable(true);txtJogador3.enable(true);
        //Habilita novas dezenas
       J1dez1.enable(true);J1dez2.enable(true);J1dez3.enable(true);
       J1dez4.enable(true);J1dez5.enable(true);J1dez6.enable(true);
       
       J2dez1.enable(true);J2dez2.enable(true);J2dez3.enable(true);
       J2dez4.enable(true);J2dez5.enable(true);J2dez6.enable(true);
       
       J3dez1.enable(true);J3dez2.enable(true);J3dez3.enable(true);
       J3dez4.enable(true);J3dez5.enable(true);J3dez6.enable(true);
        
        

    }//GEN-LAST:event_btnLimpartudoActionPerformed

    private void btnGravarJogosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarJogosActionPerformed
        String nomej1;String nomej2;String nomej3;
        
        nomej1 = txtJogador1.getText();nomej2 = txtJogador2.getText();nomej3 = txtJogador3.getText();

        //DEZENAS JOGADOR 1
        String j1dez1 = J1dez1.getText();String j1dez2 = J1dez2.getText();
        String j1dez3 = J1dez3.getText();String j1dez4 = J1dez4.getText();
        String j1dez5 = J1dez5.getText();String j1dez6 = J1dez6.getText();    
        
        //DEZENAS JOGADOR 2
        String j2dez1 = J2dez1.getText();String j2dez2 = J2dez2.getText();
        String j2dez3 = J2dez3.getText();String j2dez4 = J2dez4.getText();
        String j2dez5 = J2dez5.getText();String j2dez6 = J2dez6.getText();  
        
        //DEZENAS JOGADOR 3
        String j3dez1 = J3dez1.getText();String j3dez2 = J3dez2.getText();
        String j3dez3 = J3dez3.getText();String j3dez4 = J3dez4.getText();
        String j3dez5 = J3dez5.getText();String j3dez6 = J3dez6.getText();  
        
        
        
       
       if ("".equals(nomej1)     || j1dez1.equals(j1dez2) 
        || j1dez1.equals(j1dez3) || j1dez1.equals(j1dez4) 
        || j1dez1.equals(j1dez5) || j1dez1.equals(j1dez6) 
        || j1dez2.equals(j1dez3) || j1dez2.equals(j1dez4)
        || j1dez2.equals(j1dez5) || j1dez2.equals(j1dez6) 
        || j1dez3.equals(j1dez4) || j1dez3.equals(j1dez5) 
        || j1dez3.equals(j1dez6) || j1dez4.equals(j1dez5)
        || j1dez5.equals(j1dez6) || j1dez5.equals(j1dez6)
        || "".equals(nomej2)     || j2dez1.equals(j2dez2) 
               //jogador2
        || j2dez1.equals(j2dez3) || j2dez1.equals(j2dez4)
        || j2dez1.equals(j2dez5) || j2dez1.equals(j2dez6)
        || j2dez2.equals(j2dez3) || j2dez2.equals(j2dez4)
        || j2dez2.equals(j2dez5) || j2dez2.equals(j2dez6)
        || j2dez3.equals(j2dez4) || j2dez3.equals(j2dez5)
        || j2dez3.equals(j2dez6) || j2dez4.equals(j2dez5)
        || j2dez5.equals(j2dez6) || j2dez5.equals(j2dez6)
               //jogador 3
        
        || j3dez1.equals(j3dez3) || j3dez1.equals(j3dez4)
        || j3dez1.equals(j3dez5) || j3dez1.equals(j3dez6)
        || j3dez2.equals(j3dez3) || j3dez2.equals(j3dez4)
        || j3dez2.equals(j3dez5) || j3dez2.equals(j3dez6)
        || j3dez3.equals(j3dez4) || j3dez3.equals(j3dez5)
        || j3dez3.equals(j3dez6) || j3dez4.equals(j3dez5)
        || j3dez5.equals(j3dez6) || j3dez5.equals(j3dez6)
        || "".equals(nomej3)
               ){
        
           JOptionPane.showMessageDialog(null, "Não é possivel repetir valores ou em branco!");

       }else{ 
                int j1dz1 = Integer.parseInt(J1dez1.getText());
        int j1dz2 = Integer.parseInt(J1dez2.getText());
        int j1dz3 = Integer.parseInt(J1dez3.getText());
        int j1dz4 = Integer.parseInt(J1dez4.getText());
        int j1dz5 = Integer.parseInt(J1dez5.getText());
        int j1dz6 = Integer.parseInt(J1dez6.getText());
        
        int j2dz1 = Integer.parseInt(J2dez1.getText());
        int j2dz2 = Integer.parseInt(J2dez2.getText());
        int j2dz3 = Integer.parseInt(J2dez3.getText());
        int j2dz4 = Integer.parseInt(J2dez4.getText());
        int j2dz5 = Integer.parseInt(J2dez5.getText());
        int j2dz6 = Integer.parseInt(J2dez6.getText());
        
        int j3dz1 = Integer.parseInt(J3dez1.getText());
        int j3dz2 = Integer.parseInt(J3dez2.getText());
        int j3dz3 = Integer.parseInt(J3dez3.getText());
        int j3dz4 = Integer.parseInt(J3dez4.getText());
        int j3dz5 = Integer.parseInt(J3dez5.getText());
        int j3dz6 = Integer.parseInt(J3dez6.getText());
        
        if(    //=====JOGADOR1
               j1dz1 > 60 || j1dz1 < 1 
            || j1dz2 > 60 || j1dz2 < 1 
            || j1dz3 > 60 || j1dz3 < 1 
            || j1dz4 > 60 || j1dz4 < 1 
            || j1dz5 > 60 || j1dz5 < 1 
            || j1dz6 > 60 || j1dz6 < 1 
                //=====JOGADOR2
            || j2dz1 > 60 || j2dz1 < 1 
            || j2dz2 > 60 || j2dz2 < 1 
            || j2dz3 > 60 || j2dz3 < 1 
            || j2dz4 > 60 || j2dz4 < 1 
            || j2dz5 > 60 || j2dz5 < 1 
            || j2dz6 > 60 || j2dz6 < 1
                //=====JOGADOR3
            || j3dz1 > 60 || j3dz1 < 1 
            || j3dz2 > 60 || j3dz2 < 1 
            || j3dz3 > 60 || j3dz3 < 1 
            || j3dz4 > 60 || j3dz4 < 1 
            || j3dz5 > 60 || j3dz5 < 1 
            || j3dz6 > 60 || j3dz6 < 1
                ){
             JOptionPane.showMessageDialog(null, "DEZENAS DEVEM SER MENORES OU IGUAL A 60 !!!");
        }else{
            
            //Concatena dezenas j1
       String njogador1 = txtJogador1.getText().trim();
       String dezenas = J1dez1.getText().trim()+" "+J1dez2.getText().trim()+" "+J1dez3.getText().trim()
               +" "+J1dez4.getText().trim()+" "+J1dez5.getText().trim()+" "+J1dez6.getText().trim();
        //Concatena dezenas j2
       String njogador2 = txtJogador2.getText().trim();
       String dezenas2 = J2dez1.getText().trim()+" "+J2dez2.getText().trim()+" "+J2dez3.getText().trim()
               +" "+J2dez4.getText().trim()+" "+J2dez5.getText().trim()+" "+J2dez6.getText().trim();
       
        //Concatena dezenas j3
       String njogador3 = txtJogador3.getText().trim();
       String dezenas3 = J3dez1.getText().trim()+" "+J3dez2.getText().trim()+" "+J3dez3.getText().trim()
               +" "+J3dez4.getText().trim()+" "+J3dez5.getText().trim()+" "+J3dez6.getText().trim();
             
       //instancia tabela
        DefaultTableModel val = (DefaultTableModel) tbJogosfeitos.getModel();
        //adciona linhas e colunas
        val.addRow(new String[]{njogador1,dezenas});
        val.addRow(new String[]{njogador2,dezenas2});
        val.addRow(new String[]{njogador3,dezenas3});
      
       //Desabilita novos jogadores
       txtJogador1.enable(false);txtJogador2.enable(false);txtJogador3.enable(false);
        //Desabilita novas dezenas
       J1dez1.enable(false);J1dez2.enable(false);J1dez3.enable(false);
       J1dez4.enable(false);J1dez5.enable(false);J1dez6.enable(false);
       J2dez1.enable(false);J2dez2.enable(false);J2dez3.enable(false);
       J2dez4.enable(false);J2dez5.enable(false);J2dez6.enable(false);
       J3dez1.enable(false);J3dez2.enable(false);J3dez3.enable(false);
       J3dez4.enable(false);J3dez5.enable(false);J3dez6.enable(false);
       btnGerarSorteio.enable(true);
       
       }
       }
       
    }//GEN-LAST:event_btnGravarJogosActionPerformed

    private void J1dez1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_J1dez1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_J1dez1ActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField J1dez1;
    private javax.swing.JTextField J1dez2;
    private javax.swing.JTextField J1dez3;
    private javax.swing.JTextField J1dez4;
    private javax.swing.JTextField J1dez5;
    private javax.swing.JTextField J1dez6;
    private javax.swing.JTextField J2dez1;
    private javax.swing.JTextField J2dez2;
    private javax.swing.JTextField J2dez3;
    private javax.swing.JTextField J2dez4;
    private javax.swing.JTextField J2dez5;
    private javax.swing.JTextField J2dez6;
    private javax.swing.JTextField J3dez1;
    private javax.swing.JTextField J3dez2;
    private javax.swing.JTextField J3dez3;
    private javax.swing.JTextField J3dez4;
    private javax.swing.JTextField J3dez5;
    private javax.swing.JTextField J3dez6;
    private javax.swing.JPanel PainelNumerosorteados;
    private javax.swing.JPanel PainelResultadoganhador;
    private javax.swing.JPanel Paineldosjogadores;
    private javax.swing.JPanel Painelprincipal;
    private javax.swing.JLabel acertos;
    private javax.swing.JButton btnGerarSorteio;
    private javax.swing.JButton btnGravarJogos;
    private javax.swing.JButton btnLimpartudo;
    private javax.swing.JButton btnResultado;
    private javax.swing.JLabel dezna1;
    private javax.swing.JLabel dezna2;
    private javax.swing.JLabel dezna3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane23;
    private javax.swing.JLabel jogador1;
    private javax.swing.JLabel jogador2;
    private javax.swing.JLabel jogador3;
    private javax.swing.JLabel nom1;
    private javax.swing.JPanel tbControles;
    private javax.swing.JTable tbJogosfeitos;
    private javax.swing.JTextField txtAcerJogadorj1;
    private javax.swing.JTextField txtAcerJogadorj2;
    private javax.swing.JTextField txtAcerJogadorj3;
    private javax.swing.JTextField txtJogador1;
    private javax.swing.JTextField txtJogador2;
    private javax.swing.JTextField txtJogador3;
    private javax.swing.JTextField txtNomeJogador1;
    private javax.swing.JTextField txtNomeJogador2;
    private javax.swing.JTextField txtNomeJogador3;
    private javax.swing.JLabel txtResu;
    private java.awt.List txtSorteioNum;
    // End of variables declaration//GEN-END:variables

    /**
     *
     * @param i the value of i
     */
    private String toString(int[] i) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
